SCALPING_CONFIG = {
    "RSI_ENTRY_THRESHOLD": 35,
    "RSI_EXIT_THRESHOLD": 60,
    "SLIPPAGE_TOLERANCE": 0.004,  # 0.4%
    "MAX_POSITION_DURATION_MINUTES": 15,
    "VOLUME_SMA_PERIOD": 25,
    "CANDLE_INTERVAL": "1m",
    "RSI_PERIOD": 14,
    "EMA_PERIOD": 14,
    "MACD_FAST": 12,
    "MACD_SLOW": 26,
    "MACD_SIGNAL": 9,
    "ATR_PERIOD": 14,
    "MAX_SCALE_COUNT": 2,
    "TP_MULTIPLIER": 1.2,
    "SL_MULTIPLIER": 1.0,
}
