SCALPING_CONFIG = {
    "RSI_ENTRY_THRESHOLD": 50,
    "RSI_EXIT_THRESHOLD": 58,
    "SLIPPAGE_TOLERANCE": 0.004,  # 0.4%
    "MAX_POSITION_DURATION_MINUTES": 15,
    "VOLUME_SMA_PERIOD": 20,
    "CANDLE_INTERVAL": "1m",
    "RSI_PERIOD": 7,
    "EMA_PERIOD": 9,
    "MACD_FAST": 12,
    "MACD_SLOW": 26,
    "MACD_SIGNAL": 9,
    "ATR_PERIOD": 14,
}
